/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
    BFormCheckboxGroup: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckboxGroup']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormInvalidFeedback: typeof import('bootstrap-vue-next/components/BForm')['BFormInvalidFeedback']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BTab: typeof import('bootstrap-vue-next/components/BTabs')['BTab']
    BTabs: typeof import('bootstrap-vue-next/components/BTabs')['BTabs']
    ChartsTab: typeof import('./src/components/report/tabs/ChartsTab.vue')['default']
    CountryAvailabilityChart: typeof import('./src/components/report/charts/CountryAvailabilityChart.vue')['default']
    GenreStatisticsTab: typeof import('./src/components/report/tabs/GenreStatisticsTab.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LineChart: typeof import('./src/components/charts/LineChart.vue')['default']
    OverviewTab: typeof import('./src/components/report/tabs/OverviewTab.vue')['default']
    PieChart: typeof import('./src/components/charts/PieChart.vue')['default']
    ProductionYearsChart: typeof import('./src/components/report/charts/ProductionYearsChart.vue')['default']
    ReportResultModal: typeof import('./src/components/report/ReportResultModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TopKeywordsTab: typeof import('./src/components/report/tabs/TopKeywordsTab.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
    YearStatisticsTab: typeof import('./src/components/report/tabs/YearStatisticsTab.vue')['default']
  }
}
